pipeline:
  name: githubbugcheck
  identifier: githubbugcheck
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Test
        identifier: Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: Aditya_Standard_Type_Cluster
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: bash
                    shell: Sh
                    command: echo <+eventPayload.repository.name>
    - stage:
        name: Echo
        identifier: Echo
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |
                          # #!/bin/bash

                          # # Check if Git is installed
                          # if command -v git &> /dev/null; then
                          #     echo "Git is already installed."
                          # else
                          #     echo "Git not found. Installing Git..."

                          #     # Update the system and install required dependencies
                          #     sudo yum update -y

                          #     # Install Git using YUM
                          #     sudo yum install git -y

                          #     # Verify Git installation
                          #     if command -v git &> /dev/null; then
                          #         echo "Git installed successfully."
                          #     else
                          #         echo "Error: Git installation failed."
                          #         exit 1
                          #     fi
                          # fi



                          microdnf install git -y

                              # Verify installation
                              if command -v git &> /dev/null; then
                                  echo "Git installed successfully."
                              else
                                  echo "Error: Git installation failed."
                                  exit 1
                              fi
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  variables:
    - name: var1
      type: String
      description: ""
      required: false
      value: <+input>
  properties:
    ci:
      codebase:
        connectorRef: account.Aditya_Github_Account_Connector
        repoName: <+eventPayload.repository.name>
        build: <+input>
