pipeline:
  name: BitBucket Test
  identifier: BitBucket_Test
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Test
        identifier: Test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo <+trigger.payload.repository.slug>                          
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
        when:
          pipelineStatus: Success
